/* Separate supplemental track, based on the supplied AI Engineer resume. */
window.RESUME_PATH = (() => {
  const paths=[
    {name:'1. MFlash: classification, ranking, and safe actions',focus:'Your résumé describes a 290,890-parameter classifier with 74 templates, an MPNet ranker with 1.05M trainable parameters, four capability adapters, and five model-assisted file operations.',ids:['ml-decisions','embeddings-ranking','durable-agents','protocols','ai-security','design-mflash'],practice:'Trace one request from an intent label to eligible capabilities, ranked candidates, validation, and a receipt. Implement confidence-based abstention and show a retry that does not duplicate an operation. Explain what each parameter count includes.',evidence:'Bring the model configuration, template split, held-out evaluation, thresholds, and one cancellation or recovery example. Separate model accuracy from execution success.'},
    {name:'2. NoteEchoes: local models, adaptation, and recovery',focus:'Your résumé describes Flutter/Dart/Swift, Qwen3, SQLite, three languages, multimodal ingestion, OCR, knowledge graphs, and retrieval-grounded answers. It reports 96.3% action-field exact match and 100% schema validity on 1,080 synthetic evaluation cases.',ids:['modern-transformers','inference','adaptation','local-ai','speech','documents-multimodal','design-noteechoes'],practice:'Follow one note from audio or image ingestion to stored evidence and a validated action. Work through a memory budget, a LoRA parameter example, SQLite persistence, and restart recovery. Distinguish schema validity from correct field values.',evidence:'Bring the exact checkpoint, adapter configuration, device measurements, evaluation split, and per-language results. Keep the synthetic-data qualification attached to the reported metrics.'},
    {name:'3. Agentic RAG: retrieval, graph state, and evaluation',focus:'Your résumé names LangGraph, Claude API, Pinecone, FastAPI, asynchronous retrieval, self-correcting search, and Ragas evaluation.',ids:['retrieval-indexes','advanced-rag','context','agent-evals','durable-agents','production'],practice:'Build a small baseline before adding another agent. Trace a question through retrieval, reranking, evidence selection, generation, and evaluation. Add one retrieval failure, one timeout, and a stopping rule for repeated search.',evidence:'Bring a retrieval dataset, relevance labels, supported-answer examples, a failure trace, and quality/latency measurements. Explain your own contribution to each component.'},
    {name:'4. Bank of America: extraction and enterprise workflows',focus:'Your résumé describes OCR and JSON extraction, fine-tuning contributions, a React validation UI, MCP document retrieval, OpenText workflows/WebReports, Alteryx integration, and Excel-to-JSON validation APIs.',ids:['documents-multimodal','context','evaluation-data','protocols','data-engineering','production','design-enterprise'],practice:'Trace a document or spreadsheet from retrieval through parsing, validation, human correction, approval, and downstream submission. Keep stable document/deal IDs, schema versions, and per-field errors. Separate a retryable request from an already-completed submission.',evidence:'Explain the denominator and baseline behind the estimated 50–60% and 30–40% reductions. Bring sanitized schemas and validation examples, not confidential production data. State where a human remained responsible.'},
    {name:'5. Sedin: Spark, APIs, and classical NLP',focus:'Your résumé describes Databricks/Spark/PySpark/SQL processing 5 TB+ daily, FastAPI/Django/Node.js services, and TF-IDF/PageRank summarization evaluated with ROUGE.',ids:['data-engineering','classical-ranking','evaluation-data','production','distributed-training'],practice:'Explain partitioning, joins, skew, incremental ingestion, data quality, and replay using a small dataset. Then work one TF-IDF example, one PageRank update, and one ROUGE comparison. Treat distributed model training as optional extension after the Spark topics.',evidence:'Bring a pipeline diagram, query plan, a bottleneck and its measurement, and the unit behind the daily volume. Explain why ROUGE overlap alone cannot establish factual correctness.'},
    {name:'6. Cactus and earlier projects: security and integration',focus:'Your résumé describes a React file-sharing app for approximately 200 users and files up to 10 MB, Cognito authentication, encrypted S3 storage, recipient-only decryption, DynamoDB audit metadata, and earlier Raspberry Pi/Electron/Alexa/Lambda work.',ids:['ai-security','production','design-platform','speech','interview-evidence'],practice:'Draw upload, encryption, key delivery, authorized download, revocation, and audit flows. Explain what happens when access is removed after sharing. For the voice project, trace invocation, request validation, device response, and user-visible latency.',evidence:'Define the trust boundary and key ownership. Qualify “100% accuracy” by its original test scope and denominator. Explain the architecture you actually built before proposing improvements.'}
  ];
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function render(){return `<section class="resume-path"><h2>Study your résumé in this order</h2><p>Your original Days 1–30 remain on the dashboard. Work through one project below as additional preparation. Each linked chapter contains the full mechanism, worked examples, failure cases, interview questions, and an exercise; opening it does not change your daily checkboxes.</p>${paths.map(p=>`<details><summary>${esc(p.name)}</summary><p>${esc(p.focus)}</p><ol>${p.ids.map(id=>{const c=AI_DEPTH.chapters.find(c=>c.id===id);return `<li><a href="#${id}">${esc(c.title)}</a></li>`;}).join('')}</ol><p><b>Build and explain:</b> ${esc(p.practice)}</p><p><b>Evidence to prepare:</b> ${esc(p.evidence)}</p><p>For each chapter: read the full explanation, calculate the worked example, run the code where provided, answer the interview questions without looking, and write your evidence note. Continue when you can explain it; there is no fixed 20-minute completion claim.</p></details>`).join('')}</section>`;}
  return {render};
})();
