/* One study workflow and the dashboard's existing progress store. */
window.DAILY_STUDY = (() => {
  const KEY='orbit-ai-progress-v1', CHECKPOINT='days-1-5-except-design-2026-10-06';
  const {topicIds,answers}=DAILY_LESSON_CONTENT;
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const stages=[{id:'learn',name:'AI lesson',keys:['reading','lab','localai'],time:'25 min'}, {id:'coding',name:'Coding',keys:['coding'],time:'35 min'}, {id:'design',name:'System design',keys:['design'],time:'25 min'}, {id:'explain',name:'Explain it',keys:['recall'],time:'10 min'}];
  let state={days:{},last:1}, timer=null, playing=false, voice=false, slide=0, slides=[];
  const design=[
    ['Start a design answer with the user’s goal, then turn it into a small system. For a notes app, begin with saving and finding notes; do not start by listing cloud products.', 'Clarify: who uses it, what must it do, and what is out of scope?','Define: write the main request, response, and stored record.','Draw: client → API → database, then trace one request.','Stress: choose one scale or failure constraint and explain the change.'],
    ['An API is a contract between a caller and a service. For creating a note, define what the caller sends, what success returns, and what happens on retry.', 'Specify POST /notes with text and an authenticated user.','Return a stable note ID; validate size and required fields.','Distinguish invalid input, denied access, and temporary failure.','Use an idempotency key when a retry must not create another note.'],
    ['A data model describes records and their relationships. A notes app might have users, notes, and tags. Start with the queries the app must support.', 'Give every note an ID, owner, content, and version.','Use a separate relationship table if one note has many tags.','Keep ownership and access rules explicit.','Explain what happens to related records when a note is deleted.'],
    ['A cache keeps a reusable result closer to the request. It speeds up repeated reads, but a stale or incorrectly shared result can be worse than no cache.', 'Choose one cached item, such as the latest public document summary.','Include document version and access scope in the cache key.','Set a freshness rule: expiry, invalidation on write, or both.','Handle a miss by reading the source; prevent many misses from overwhelming it.'],
    ['A database index helps find records without scanning every row. Its ordering should match an important query, and writes must maintain the index.', 'Example query: one user’s notes ordered by creation time.','Consider an index beginning with owner_id, then created_at.','Explain the extra storage and write cost.','Inspect a query plan and realistic data before claiming it is faster.'],
    ['A rate limiter prevents one caller from consuming all capacity. Separate the identity being limited from the counting algorithm.', 'Choose a scope: user, account, API key, or address.','Define an average allowance and permitted bursts.','Compare fixed windows with a token bucket.','Make counter updates atomic and return a useful retry response.'],
    ['Rehearse a complete small system under a time limit. Depth in one bottleneck is more useful than a long list of components.', 'Spend five minutes clarifying requirements.','Draw a minimal request and data flow.','Calculate one storage or throughput budget.','Use the remaining time for a failure, a tradeoff, and evaluation.'],
    ['Streaming sends results incrementally. Decide whether the user needs one-way updates or a two-way connection, and plan for disconnection.', 'Compare polling, server-sent events, and WebSockets.','Give events IDs so a client can detect repeats or gaps.','Bound buffers when a consumer is slow.','Explain resuming a connection without duplicating actions.'],
    ['A vector database stores searchable representations with source metadata. The index is one part of the retrieval system.', 'Choose embedding compatibility and a similarity metric.','Keep source IDs, versions, and access filters.','Compare approximate retrieval against exact search.','Plan updates, deletion, and an embedding-model migration.'],
    ['Design search as candidate retrieval followed by ranking. Measure whether useful results are found, not just whether requests succeed.', 'Parse documents while preserving their structure.','Compare lexical and semantic candidates.','Rerank a bounded set and return source evidence.','Measure recall, ordering, latency, and permission failures.'],
    ['Ingestion turns changing source files into useful derived data. Duplicates and out-of-order updates must have a defined outcome.', 'Use a stable source ID and version for every job.','Preserve the original before extraction.','Deduplicate retries with a persistent operation identity.','Reject stale results when a newer source version exists.'],
    ['Long-running jobs should survive a lost connection or worker restart. Separate job submission from job execution.', 'Return a job ID after accepting work.','Store queued, running, completed, failed, and unknown states.','Checkpoint resumable stages and bound retries.','Support cancellation without pretending completed effects were undone.'],
    ['A scheduler decides when work runs and which worker owns it. Ownership must remain clear when workers fail or become slow.', 'Store due time, job identity, and retry policy.','Claim work atomically with a lease or equivalent control.','Handle a worker that runs after its lease expires.','Deduplicate effects and expose exhausted jobs for review.'],
    ['Design a document assistant that answers from authorized evidence. Separate retrieval failure from answer-generation failure.', 'Define document types and question categories.','Ingest, chunk, index, retrieve, and rerank.','Answer with citations or say what is missing.','Evaluate retrieval, answer support, cost, and access control.'],
    ['A multi-step workflow has explicit state and transition rules. Use model decisions only where the next step really depends on interpretation.', 'Write the steps and their required inputs.','Persist results before dependent work begins.','Define which stages are safe to retry.','Specify what happens after partial completion.'],
    ['A tool contract defines an operation precisely enough to validate and test. A model-generated tool call is a proposal.', 'Define arguments, types, units, and required fields.','State permissions and side effects.','Document timeouts, idempotency, and cancellation.','Return structured outcomes rather than only a success sentence.'],
    ['Security and consistency meet at the moment an action executes. Previously retrieved information does not grant permanent permission.', 'Check the current user’s access to the exact resource.','Bind approval to the concrete action and arguments.','Check resource versions before changing them.','Record outcomes and distinguish denied, failed, and unknown work.'],
    ['A retry can duplicate an action if the first attempt succeeded but its response was lost. Reconciliation resolves that uncertainty.', 'Reuse the same operation key for the same intended work.','Reject key reuse with different arguments.','Query the service or receipt store after an uncertain result.','Stop for review when the outcome cannot be established.'],
    ['Choose adaptation only after identifying a behavior gap. Compare its full lifecycle with prompting or retrieval.', 'Define the failure and a measurable baseline.','Prepare representative independent evaluation data.','Choose what parameters to train and estimate memory.','Test the actual exported artifact and a rollback path.'],
    ['Serving caches can reuse prompt work or complete answers, but those are different contracts.', 'Distinguish KV, prefix, and response caches.','Include model and relevant data versions in cache identity.','Isolate users and permission scopes.','Measure hit rate, first-token latency, quality, and stale responses.'],
    ['Explain NoteEchoes as one end-to-end user journey. Separate what shipped from a proposed improvement.', 'Trace audio or text into a stored note.','Show retrieval and the model proposal.','Explain validation, permissions, and execution.','Discuss device memory, interruption, and per-language evaluation.'],
    ['Design a conversational AI service from request intake to a streamed reply. The model is only one component.', 'Authenticate the user and load permitted history.','Assemble bounded context and route the model request.','Stream tokens while handling disconnects and deadlines.','Measure quality, queueing, cost, and privacy boundaries.'],
    ['Capacity planning connects demand, service time, and resource limits. Observability reveals which stage breaks that plan.', 'Define traffic and input/output-length assumptions.','Measure stage timings and tail latency under load.','Bound concurrency and shed work before overload.','Track outcome quality and release versions alongside errors.'],
    ['Relational correctness comes before tuning. Explain joins, transactions, and indexes against a real query.', 'Define what one row represents.','Check join cardinality and duplicate expansion.','Choose transaction boundaries and isolation needs.','Use EXPLAIN and realistic data to evaluate an index.'],
    ['A voice assistant crosses audio, text, intent, and action boundaries. Each boundary can introduce a different error.', 'Capture audio with format and permission checks.','Distinguish partial transcripts from final text.','Clarify ambiguous names and dates before action.','Measure recognition, entity accuracy, latency, and interruption.'],
    ['A distributed cache partitions reusable data across machines. Nodes fail, values expire, and hot keys can dominate traffic.', 'Choose partitioning and replication policies.','Define expiry and invalidation rules.','Handle node loss, cold starts, and stampedes.','Explain consistency requirements and fallback to the source.'],
    ['Practice an AI design with a changed requirement. Show how the architecture responds instead of repeating a fixed diagram.', 'Clarify task success and data permissions.','Choose a simple baseline pipeline.','Add a tenfold traffic increase or an offline requirement.','Revise the design and evaluation without inventing measurements.'],
    ['Use your capstone to connect model quality with application reliability. Show a good case and a failure.', 'Trace inputs, state, and outputs.','Explain the baseline and chosen intervention.','Demonstrate one failure and its recovery.','Define release criteria and remaining limitations.'],
    ['Repair the weakest part of an earlier mock. Focus the session on one missing explanation or incorrect assumption.', 'Select a specific failure from your notes.','Reconstruct the mechanism with a small example.','Change one requirement and reason through it.','Write evidence that the explanation is now correct.'],
    ['An unfamiliar design prompt tests transferable reasoning. Use the same structure without assuming a memorized architecture.', 'Clarify users, actions, and constraints.','Draw the simplest complete flow.','Estimate one important resource budget.','Defend a bottleneck, failure policy, and measurement plan.']
  ];
  function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback;}catch{return fallback;}}
  const previous=read(KEY,{});if(previous&&typeof previous==='object'&&!Array.isArray(previous))state={...state,...previous};
  if(!state.days||typeof state.days!=='object'||Array.isArray(state.days))state.days={};
  function day(d){const old=state.days[d];if(!old||typeof old!=='object')state.days[d]={checks:{},notes:''};const x=state.days[d];if(!x.checks||typeof x.checks!=='object')x.checks={};if(!x.unifiedNotes||typeof x.unifiedNotes!=='object')x.unifiedNotes={};return x;}
  function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));return 'Saved in this browser. Export progress to move future updates between devices.';}catch{return 'Browser saving is unavailable. Export progress before closing this page.';}}
  const legacy=read('orbit-ai-daily-v1',{});
  if(!state.unifiedNotesImported){for(let d=1;d<=30;d++){if(typeof legacy[d]?.note==='string'&&!day(d).unifiedNotes.learn)day(d).unifiedNotes.learn=legacy[d].note;}state.unifiedNotesImported=true;}
  // User explicitly reported this checkpoint. Apply once per progress store, not on every visit.
  if(!state[CHECKPOINT]){for(let d=1;d<=5;d++){const x=day(d);for(const k of ['reading','coding','lab','localai','recall'])x.checks[k]=true;x.checks.design=false;delete x.unifiedStage;}state[CHECKPOINT]=true;state.last=6;persist();}
  const done=(d,s)=>stages[s].keys.every(k=>day(d).checks[k]===true);
  const complete=d=>stages.every((_,s)=>done(d,s));
  function next(){for(let d=1;d<=30;d++)if(!complete(d))return d;return 30;}
  function cleanup(){clearTimeout(timer);timer=null;playing=false;if(window.speechSynthesis)window.speechSynthesis.cancel();}
  function md(text){const blocks=[];text=text.replace(/^```[^\n]*\n[\s\S]*?^```/gm,m=>{blocks.push(marked.parse(m));return '\n\nSTUDYBLOCK'+(blocks.length-1)+'END\n\n';});text=text.replace(/^\$\$ (.+) \$\$$/gm,(_,m)=>{blocks.push('<div class="equation">'+katex.renderToString(m,{displayMode:true,throwOnError:false})+'</div>');return '\n\nSTUDYBLOCK'+(blocks.length-1)+'END\n\n';});text=text.replace(/\$([^$\n]+)\$/g,(_,m)=>katex.renderToString(m,{throwOnError:false}));return marked.parse(text).replace(/<p>STUDYBLOCK(\d+)END<\/p>/g,(_,i)=>blocks[+i]);}
  function safeProgress(value){
    if(!value||typeof value!=='object'||!value.days||Array.isArray(value.days))throw Error('Not a study-progress file.');
    const result={...state,days:{...state.days}};
    for(let d=1;d<=30;d++){const v=value.days[d];if(!v||typeof v!=='object')continue;const old=day(d);const x={...old,checks:{...old.checks},unifiedNotes:{...old.unifiedNotes}};for(const k of ['reading','coding','design','lab','recall','localai'])if(typeof v.checks?.[k]==='boolean')x.checks[k]=v.checks[k];if(typeof v.notes==='string')x.notes=v.notes.slice(0,30000);for(const s of stages)if(typeof v.unifiedNotes?.[s.id]==='string')x.unifiedNotes[s.id]=v.unifiedNotes[s.id].slice(0,30000);if(Number.isInteger(v.unifiedStage)&&v.unifiedStage>=0&&v.unifiedStage<4)x.unifiedStage=v.unifiedStage;result.days[d]=x;}
    result[CHECKPOINT]=true;return result;
  }
  function render(d){
    cleanup();const x=day(d),g=LESSON_GUIDES[d-1],lesson=BEGINNER[d-1],plan=DAYS[d-1],chapter=AI_DEPTH.chapters.find(c=>c.id===topicIds[d-1]);
    const first=stages.findIndex((_,i)=>!done(d,i));const stage=Number.isInteger(x.unifiedStage)&&x.unifiedStage>=0&&x.unifiedStage<4?x.unifiedStage:Math.max(0,first);x.unifiedStage=stage;
    const route=CODING_ROUTES[d],href=route.url.startsWith('https:')?route.url:'../'+route.url;
    const sections=lesson.body.split(/(?=^### )/m).filter(x=>x.trim()),example=sections.find(s=>s.includes('```python'))||sections[1]||sections[0];
    const qa=chapter.body.split('## Interview rehearsal\n')[1].split('## Prove it yourself\n')[0].trim().split(/^### /m).filter(Boolean)[0];const q=qa.indexOf('\n');
    const backlog=Array.from({length:5},(_,i)=>i+1).filter(n=>!done(n,2));const count=stages.filter((_,i)=>done(d,i)).length;
    document.title=`Day ${d} · ${stages[stage].name} · Orbit Study`;
    document.querySelector('#lesson').innerHTML=`<div class="study-top"><span>YOUR ONE STUDY PLAN</span><a href="#day-6">Go to Day 6 →</a></div>
    <h1>Day ${d}: ${esc(g.title)}</h1><p class="lead">Follow these four steps. The AI explanation, coding, design, and your project story are all here.</p>
    <div class="checkpoint"><b>Saved checkpoint: Days 1–5 complete except system design.</b><p>${backlog.length?`${backlog.length} design sessions still pending. Catch up one at a time below, or continue Day 6.`:'Your first five design sessions are now marked complete.'}</p>${backlog.length?`<div class="catchup">${backlog.map(n=>`<button data-catchup="${n}">Day ${n} · ${esc(DAYS[n-1].label)}</button>`).join('')}</div>`:''}</div>
    <details class="day-picker"><summary>Choose a day · ${count}/4 steps complete today</summary><div class="day-grid">${LESSON_GUIDES.map(a=>`<a href="#day-${a.day}" ${a.day===d?'aria-current="page"':''}><b>${complete(a.day)?'✓ ':''}Day ${a.day}</b><span>${esc(a.title)}</span><small>${stages.filter((_,i)=>done(a.day,i)).length}/4 steps</small></a>`).join('')}</div></details>
    <nav class="study-steps" aria-label="Daily study order">${stages.map((s,i)=>`<button data-study-step="${i}" aria-pressed="${i===stage}"><span>${done(d,i)?'✓':i+1}</span><b>${s.name}</b><small>${s.time}</small></button>`).join('')}</nav>
    <p class="study-instruction">${stage===2&&d<=5&&!done(d,2)?'This is the unfinished part of this day. You do not need to redo the other steps.':`Step ${stage+1} of 4 · ${done(d,stage)?'Already marked complete. You can review it.':'Do this step, then continue. Times are suggestions, not deadlines.'}`}</p>
    <section class="study-stage">
    ${stage===0?`<p class="kicker">UNDERSTAND TODAY’S AI IDEA</p><h2>${esc(g.summary)}</h2><div class="prose">${md(sections.slice(0,2).join('\n'))}</div><div class="simple-example"><b>Small example</b><p>${esc(g.example)}</p></div><details><summary>Work through the code example</summary><div class="prose">${md(example)}</div><a href="../beginner/labs/${lesson.lab}" download>Download this example</a></details><details><summary>Full explanation for today</summary><div class="prose">${md(lesson.body)}</div></details>`:''}
    ${stage===1?`<p class="kicker">ONE CODING ASSIGNMENT</p><h2>${esc(plan.coding)}</h2><p>Spend a few minutes describing the inputs and expected output. Try a simple correct solution, test edge cases, then explain the time and space cost.</p><ol><li>Work one small example by hand.</li><li>Write your own attempt before opening the reference solution.</li><li>Test an empty, boundary, or duplicate case when relevant.</li><li>Explain why your code works and what it costs.</li></ol><a class="button primary" href="${esc(href)}" target="_blank" rel="noopener noreferrer">Open today’s exercise · ${esc(route.provider)} ↗</a><p class="muted">The exercise opens in another tab. Return here to record completion. Code Lab includes line-by-line explanations and visual walkthroughs.</p>`:''}
    ${stage===2?`<p class="kicker">TODAY’S SYSTEM DESIGN</p><h2>${esc(plan.label)}</h2><p class="lead">${esc(design[d-1][0])}</p><ol class="design-recipe">${design[d-1].slice(1).map(s=>`<li>${esc(s)}</li>`).join('')}</ol><div class="simple-example"><b>Your task</b><p>Draw a small system for this topic. Label the inputs, stored state, output, and one failure. Explain one tradeoff aloud.</p></div><a class="button" href="${esc(plan.design)}" target="_blank" rel="noopener noreferrer">Read today’s design lesson · Hello Interview ↗</a><p class="muted">Some external lessons may require your existing account. Use the steps above as your local study worksheet.</p>`:''}
    ${stage===3?`<p class="kicker">INTERVIEW + PROJECT PRACTICE, TOGETHER</p><h2>${esc(g.check)}</h2><p>Give a two-minute answer: the idea, one example, and one failure. Connect it to ${esc(chapter.projects.join(' or '))} where you have real experience.</p><details><summary>Show a plain-language answer</summary><p>${esc(answers[d-1])}</p></details><details><summary>Your interview follow-up: ${esc(qa.slice(0,q))}</summary><div class="prose">${md(qa.slice(q+1))}</div></details><p><b>For your résumé:</b> State your actual contribution, the baseline, how you measured the result, and a limitation. If you do not have a measurement, say so. This is today’s project practice; there is no second résumé lesson to finish.</p>`:''}
    <section class="walkthrough"><h3>Watch the idea unfold</h3><p class="muted">A short slide walkthrough with captions. Optional narration uses a voice available in your browser; this is not a recorded video.</p><div class="walk-caption" aria-live="polite"></div><div class="walk-controls"><button id="walk-play">▶ Play walkthrough</button><button id="walk-next">Next frame →</button><label><input id="walk-voice" type="checkbox"> Narration</label><span id="walk-position"></span></div><p id="walk-status" class="muted" role="status"></p></section>
    <label for="study-note">One note for this step</label><textarea id="study-note" placeholder="What I understood, what I tried, or what I need to revisit…" maxlength="30000"></textarea><p id="study-save" role="status"></p>
    </section><div class="study-actions"><button id="study-complete" class="primary">${done(d,stage)?'Completed ✓ · Mark unfinished':'Mark this step complete'}</button><button id="study-next">${stage<3?`Next: ${stages[stage+1].name} →`:'Next unfinished step →'}</button></div>
    <details class="extra-reference"><summary>Optional extra explanation — not another assignment</summary><p>Use this only if you want more depth. Your required work is the four-step checklist above.</p><div class="prose">${md(chapter.body)}</div><details><summary>Sources and original interactive reference</summary><ul>${chapter.sources.map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a></li>`).join('')}</ul><a href="#${chapter.id}">Open the reference calculators and diagrams</a></details></details>
    <footer class="study-backup"><p>One progress record for AI, coding, design, and interview practice. Your reported Days 1–5 checkpoint is included in this published edition. Later updates are saved on this browser; use a backup to move them to another device.</p><button id="study-export">Export all progress</button><label for="study-import">Restore a backup<input id="study-import" type="file" accept=".json,application/json"></label><p id="study-backup-status" role="status"></p></footer>`;
    function rerender(){persist();render(d);document.querySelector('.study-steps').scrollIntoView({block:'start'});}
    document.querySelectorAll('[data-study-step]').forEach(b=>b.onclick=()=>{x.unifiedStage=+b.dataset.studyStep;rerender();});
    document.querySelectorAll('[data-catchup]').forEach(b=>b.onclick=()=>{const n=+b.dataset.catchup;day(n).unifiedStage=2;persist();if(n===d)rerender();else location.hash=`day-${n}`;});
    document.querySelector('#study-note').value=x.unifiedNotes[stages[stage].id]||'';
    document.querySelector('#study-note').oninput=e=>{x.unifiedNotes[stages[stage].id]=e.target.value;document.querySelector('#study-save').textContent=persist();};
    document.querySelector('#study-save').textContent='Changes to this checklist also use your original dashboard progress record.';
    document.querySelector('#study-complete').onclick=()=>{const value=!done(d,stage);for(const k of stages[stage].keys)x.checks[k]=value;rerender();};
    document.querySelector('#study-next').onclick=()=>{if(stage<3){x.unifiedStage=stage+1;rerender();}else{const n=next();day(n).unifiedStage=Math.max(0,stages.findIndex((_,i)=>!done(n,i)));persist();if(n===d)rerender();else location.hash=`day-${n}`;}};
    document.querySelector('#study-export').onclick=()=>document.querySelector('#export').click();
    document.querySelector('#study-import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>16000000)throw Error('Backup exceeds 16 MB.');const v=JSON.parse(await f.text());const p=v.progress||(v.days?v:null);if(!p)throw Error('Choose an exported study-progress backup.');state=safeProgress(p);persist();if(v.notes){const input=document.querySelector('#import');const transfer=new DataTransfer();transfer.items.add(f);input.files=transfer.files;input.dispatchEvent(new Event('change'));}render(d);document.querySelector('#study-backup-status').textContent='Progress restored.';}catch(error){document.querySelector('#study-backup-status').textContent=error.message;}};
    slides=stage===0?g.steps:stage===2?design[d-1].slice(1).map((s,i)=>[`Step ${i+1}`,s]):stage===1?[['Clarify','Restate the inputs, output, and constraints.'],['Trace','Predict one small example by hand.'],['Implement','Write a simple correct solution, then test boundary cases.'],['Explain','State why it works and its time and space complexity.']]:[['The idea',g.summary],['Your example',g.example],['Your explanation',answers[d-1]],['Your evidence','Connect this to your own contribution and measurements. Distinguish tested results from proposed improvements.']];
    slide=0;voice=false;paint();
    document.querySelector('#walk-play').onclick=()=>{if(playing){cleanup();paint();}else{playing=true;tick();}};
    document.querySelector('#walk-next').onclick=()=>{cleanup();slide=(slide+1)%slides.length;paint();};
    document.querySelector('#walk-voice').onchange=e=>{voice=e.target.checked;if(!voice&&window.speechSynthesis)window.speechSynthesis.cancel();if(voice&&(!window.speechSynthesis||!window.speechSynthesis.getVoices().length))document.querySelector('#walk-status').textContent='No voice is available yet; captions still play.';};
    document.querySelectorAll('#lesson table').forEach(t=>{const w=document.createElement('div');w.className='table-wrap';t.replaceWith(w);w.append(t);});
  }
  function paint(){const el=document.querySelector('.walk-caption');if(!el)return;el.innerHTML=`<b>${esc(slides[slide][0])}</b><p>${esc(slides[slide][1])}</p>`;document.querySelector('#walk-position').textContent=`${slide+1} / ${slides.length}`;document.querySelector('#walk-play').textContent=playing?'Pause walkthrough':'▶ Play walkthrough';document.querySelectorAll('.walk-caption').forEach(x=>x.dataset.frame=String(slide));}
  function tick(){if(!playing)return;paint();let delay=6000;if(voice&&window.speechSynthesis&&window.speechSynthesis.getVoices().length){const u=new SpeechSynthesisUtterance(slides[slide].join('. '));u.rate=.92;window.speechSynthesis.speak(u);delay=Math.max(6000,slides[slide].join(' ').split(/\s+/).length*500);}
    timer=setTimeout(()=>{if(slide===slides.length-1){cleanup();paint();return;}slide++;tick();},delay);}
  window.addEventListener('pagehide',cleanup);document.addEventListener('visibilitychange',()=>{if(document.hidden){cleanup();paint();}});
  return {render,next,cleanup,progress:()=>JSON.parse(JSON.stringify(state)),restore:value=>{state=safeProgress(value);persist();},export:()=>legacy,import:value=>{if(value&&typeof value==='object'){for(let d=1;d<=30;d++)if(typeof value[d]?.note==='string')day(d).unifiedNotes.learn=value[d].note.slice(0,30000);persist();}}};
})();
