"""Generate recorded execution snapshots from the exact published reference code.
No browser Python runtime is required to read or replay these teaching examples.
"""
import ast, asyncio, copy, dis, inspect, json, math, sys, types
from collections import deque
from pathlib import Path
from line_lessons import LESSONS
ROOT = Path(__file__).resolve().parent.parent

def snapshot(value, depth=0, visited=None):
    visited = set() if visited is None else visited
    if value is None or isinstance(value, (bool, str, int)):
        return value if not isinstance(value,str) or len(value)<220 else value[:220]+'…'
    if isinstance(value,float):
        return round(value,8) if math.isfinite(value) else str(value)
    if id(value) in visited: return '(shared/cyclic reference)'
    visited = visited | {id(value)}
    if isinstance(value,(types.ModuleType,types.FunctionType,type)) or inspect.isawaitable(value): return None
    if depth >= 4: return '… nested content'
    if isinstance(value,dict):
        pairs=list(value.items())
        result={str(k):snapshot(v,depth+1,visited) for k,v in pairs[:14]}
        if len(pairs)>14: result['…']=f'{len(pairs)-14} more entries'
        return result
    if isinstance(value,(list,tuple,set,deque)):
        values=sorted(value,key=repr) if isinstance(value,set) else list(value)
        result=[snapshot(v,depth+1,visited) for v in values[:16]]
        if len(values)>16:result.append(f'… {len(values)-16} more items')
        return result
    if hasattr(value,'__dict__'):
        return {'type':type(value).__name__,**{k:snapshot(v,depth+1,visited) for k,v in vars(value).items()}}
    return f'({type(value).__name__}; internal state not displayed)'

def record(problem, test, prelude):
    filename = '<walkthrough:'+problem['id']+'>'
    namespace={}
    exec(prelude,namespace)
    exec(compile(problem['solution'],filename,'exec'),namespace)
    frames=[]; count=0
    def trace(frame,event,arg):
        nonlocal count
        if frame.f_code.co_filename != filename: return trace
        if frame.f_code.co_name.startswith('<'): return trace
        if event not in ('line','return'): return trace
        # Coroutine suspension is not a completed function return.
        if event=='return' and dis.opname[frame.f_code.co_code[frame.f_lasti]] in ('YIELD_VALUE','YIELD_FROM'):
            return trace
        count+=1
        if len(frames)<350:
            state={k:snapshot(v) for k,v in frame.f_locals.items()
                   if not k.startswith('__') and not isinstance(v,(types.ModuleType,types.FunctionType,type)) and not inspect.isawaitable(v)}
            frames.append(dict(line=frame.f_lineno,event=event,function=frame.f_code.co_name,state=state,
                               **({'returned':snapshot(arg)} if event=='return' else {})))
        return trace
    previous=sys.gettrace()
    sys.settrace(trace)
    try:
        if problem['kind']=='class':
            obj=namespace[problem['fn']](*copy.deepcopy(test['init']))
            result=[]
            for op in copy.deepcopy(test['ops']):result.append(getattr(obj,op[0])(*op[1:]))
        else:
            args=copy.deepcopy(test['args'])
            if problem['tree']:args[0]=namespace['build_tree'](args[0])
            result=namespace[problem['fn']](*args)
            if inspect.isawaitable(result):result=asyncio.run(result)
    finally:sys.settrace(previous)
    return dict(input={k:v for k,v in test.items() if k!='expected'},expected=test['expected'],actual=result,
                frames=frames,truncated=count>len(frames),totalSteps=count)

def main():
    raw=(ROOT/'problems-data.js').read_text();decoder=json.JSONDecoder()
    prelude=decoder.raw_decode(raw.split('const PRELUDE_PY=',1)[1])[0]
    problems=decoder.raw_decode(raw.split('const PROBLEMS=',1)[1])[0]
    out={}
    for p in problems:
        lines=[(i+1,line) for i,line in enumerate(p['solution'].splitlines()) if line.strip()]
        notes=LESSONS[p['id']]
        assert len(lines)==len(notes),(p['id'],len(lines),len(notes))
        examples=[p['tests'][0],p['tests'][-1]]
        out[p['id']]=dict(lines=[dict(number=n,code=line,note=note) for (n,line),note in zip(lines,notes)],
                           examples=[record(p,t,prelude) for t in examples])
    (ROOT/'walkthroughs-data.js').write_text('/* Generated by tools/gen_walkthroughs.py; actual Python execution snapshots. */\nwindow.WALKTHROUGHS='+json.dumps(out,separators=(',',':'),allow_nan=False)+';\n')
    print(f'{len(out)} walkthroughs, {sum(len(x["lines"]) for x in out.values())} explained lines, {sum(len(x["examples"]) for x in out.values())} recorded examples.')

if __name__=='__main__':main()
