"""Original teaching notes and traceable company evidence, researched 2026-10-04.
Company reports are self-reported historical evidence, not verified hiring banks.
"""
SOURCES = {
 'amazon20': ('Amazon', 'Candidate report · SDE II · June 2020', 'https://leetcode.com/discuss/post/686538/amazon-sde2-jun-2020/', 'Reports LRU Cache and Number of Islands.'),
 'amazon19': ('Amazon', 'Candidate report · SDE II · October 2019', 'https://leetcode.com/discuss/post/409677/amazon-sde2-seattle-oct-2019-offer/', 'Reports meeting-room allocation and a topological-order variant.'),
 'amazon24': ('Amazon', 'Candidate report · SDE II · January 2024 process', 'https://leetcode.com/discuss/post/4807157/Amazon-SDE-2-%28Rejected%29-or-Seattle/', 'Reports Kth Largest Element.'),
 'meta_ml': ('Meta', 'Candidate report · ML SWE PhD · date unspecified', 'https://leetcode.com/discuss/post/4781802/Meta-Phone-Screen-or-ML-SWE-PhD-or-Didn%27t-Pass/', 'Reports nested weights, a deduplicated three-array merge, kth largest, and subarray-sum existence. Local exercises identify their adaptations.'),
 'meta_infra': ('Meta', 'Candidate report · SWE Infrastructure E5 · date unspecified', 'https://leetcode.com/discuss/post/5098716/meta-swe-infra-e5-full-loop-passed-by-an-ehcf/', 'Reports minimum tree depth, IP restoration, kth largest, and vertical traversal.'),
 'meta25': ('Meta', 'Candidate report · MLE screen · July 2025', 'https://www.reddit.com/r/leetcode/comments/1lp7lhl/meta_technical_screen_and_onsite/', 'Reports power and valid-word-abbreviation questions.'),
 'google_ml': ('Google', 'Candidate report · MLE L6 · date unspecified', 'https://leetcode.com/discuss/post/6010240/Google-MLEor-L6or-Interview-Experience-and-Resources-for-preparation/', 'Reports a logger-timer-style question; the local cooldown contract is an adaptation.'),
 'google_recipe': ('Google', 'Candidate report · onsite · October 2021', 'https://leetcode.com/discuss/interview-question/1504849/google-onsite/', 'Reports recipe dependency resolution.'),
 'db_sparse': ('Databricks', 'Candidate report · onsite · date unspecified', 'https://leetcode.com/discuss/post/1061323/databricks-onsite/', 'Reports sparse matrix–vector multiplication.'),
 'db_lazy': ('Databricks', 'Candidate report · L5 · date unspecified', 'https://leetcode.com/discuss/post/4254781/Databricks-India-Interview-Experience-%28L5%29-Rejected/', 'Reports lazy chained maps, reverse DAG traversal, and a depth-limited crawler.'),
 'db_counter': ('Databricks', 'Candidate report · SDE II · date unspecified', 'https://leetcode.com/discuss/post/4285067/Databricksor-SDE-2-or-India/', 'Reports top-frequency streaming, a hit counter, and crawler variants.'),
 'uber': ('Uber', 'Candidate report · phone screen · date unspecified', 'https://leetcode.com/discuss/post/406640/uber-phone-screen-lru-cache-number-of-islands/', 'Reports LRU-style caching and Number of Islands.'),
 'stripe': ('Stripe', 'Candidate report · Backend SWE · date unspecified', 'https://leetcode.com/discuss/post/7595344/', 'Reports duplicate-request handling and subscription notification scheduling.'),
 'openai': ('OpenAI', 'Candidate report · SWE · date unspecified', 'https://leetcode.com/discuss/post/5984554/SWE-interview-experience-for-openai/', 'Reports resumable iteration and an in-memory database with filtering and ordering.'),
 'ms26': ('Microsoft', 'Candidate report · Senior Azure Storage · March 2026', 'https://leetcode.com/discuss/post/8300781/', 'Reports LRU with TTL and a concurrency follow-up.'),
 'ms25': ('Microsoft', 'Candidate report · SE II · October–November 2025', 'https://leetcode.com/discuss/post/7541629/interview-experience-microsoft-sde-2l61-qvanx/', 'Reports Min Stack, parentheses validation/generation, and duplicate-number cycle detection.'),
}
# Each note: mechanism, worked trace, complexity of the actual reference, common mistake, extension.
NOTES = {
 'two-sum': ('Store each earlier value and its index. Before inserting x, look for target−x. A match uses two different positions because the current value is not stored yet.', 'For [2,7,11] and target 9, store 2→0. At index 1, the missing value is 2, so return [0,1].', 'O(n) time, O(n) space.', 'Inserting before looking up can reuse one element. Duplicate values still need distinct indices.', 'Return all distinct index pairs; explain why the output itself may be quadratic.'),
 'three-sum': ('Sort, fix one value, and move two pointers through the suffix. A negative sum needs a larger left value; a positive sum needs a smaller right value. Skip repeated anchors and left values after a match.', 'For [-2,0,1,1,2], fixing −2 finds [−2,0,2], then [−2,1,1].', 'O(n²) time; O(n) sorting workspace in Python, excluding output.', 'Do not return the same value triplet several times. The reference sorts the input in place.', 'Explain why moving both pointers after a match is also valid.'),
 'longest-substring': ('Keep a window with no repeated characters and remember each character’s last index. Move the left boundary past a repeated character only if it is inside the current window.', 'For abba, the second b moves left to index 2; the final a must not move left backward. The best length is 2.', 'O(n) time, O(u) space for u distinct characters.', 'Use max(left, previous+1), otherwise abba incorrectly expands the window.', 'Return the substring and choose a deterministic tie rule.'),
 'min-window': ('Count required multiplicities, expand right until all are satisfied, then shrink left while preserving validity. Record each smaller valid window before removing its left character.', 'For ADOBECODEBANC and ABC, ADOBEC is valid first. Later BANC is valid and shorter, so it becomes the answer.', 'O(n+m) time, O(u) space for the tracked characters.', 'Two copies of A in the target require two in the window. Empty targets need special handling.', 'Explain the difference between matched character counts and matched distinct categories.'),
 'merge-intervals': ('Sort by start. The last merged interval is the only one that can overlap the next interval. Extend its end to the larger end or start a new interval.', '[1,4] and [2,3] become [1,4], not [1,3]. Touching [1,4] and [4,5] merge under this contract.', 'O(n log n) time, O(n) space including sorted input and output.', 'Always take max of ends; nested intervals can otherwise shorten the result.', 'How would open intervals change the comparison?'),
 'kth-largest': ('Keep the k largest values using a min-heap. Its smallest member is the cutoff: the kth largest overall. heapq.nlargest also sorts those retained values for the returned list.', '[3,1,5,2], k=2 retains 3 and 5. The answer is 3, even if repeated values occur elsewhere.', 'O(n log k) time for 1<k<n, O(k) space; k=1 is O(n), k=n uses sorting.', 'Kth largest counts duplicates. It is not the kth distinct value.', 'Meta reports also mention quickselect: expected O(n), worst-case O(n²). Compare its mutation and pivot choices.'),
 'top-k-frequent': ('Count occurrences, select the k largest counts, then sort the selected values to meet the output contract. Counter.most_common breaks equal frequencies by first encounter.', '[4,4,5,6,6,6], k=2 picks 6 and 4, then returns [4,6].', 'O(n + u log k + k log k) time and O(u+k) space, with sorting when k≥u.', 'Frequency ranking and the final ascending-value output order are different.', 'Turn the batch input into a streaming counter and discuss memory for unseen keys.'),
 'search-rotated': ('At each midpoint, one half is sorted. Check whether the target lies within that half’s endpoints; keep that half only when it can contain the target.', '[4,5,6,7,0,1,2], target 0: the left half through 7 is sorted but excludes 0, so search right.', 'O(log n) time, O(1) space.', 'This logarithmic guarantee assumes distinct values.', 'Allow duplicates and explain why the worst case may become linear.'),
 'max-subarray': ('cur is the best sum ending exactly here. Either extend the previous sum or start at the current value. best remembers the greatest cur ever seen.', 'In [−3,4,−1,2], reset at 4, extend to 3, then to 5. The answer is 5.', 'O(n) time; O(n) temporary space in this reference because nums[1:] copies a slice.', 'Initialize from nums[0], not zero, so all-negative input returns its largest element.', 'Track start/end indices and remove the slice for O(1) auxiliary space.'),
 'trapping-rain': ('Move the pointer at the lower boundary. A sufficiently tall opposite boundary already exists, so the running maximum on this side determines trapped water here.', '[3,0,3] has a middle gap of 3−0=3; the two boundaries hold it.', 'O(n) time, O(1) space.', 'Water above a bar cannot be negative. Update the running boundary before adding water.', 'Derive the prefix/suffix maxima solution first, then eliminate its arrays.'),
 'container-water': ('Area is width times the shorter height. Move the shorter side inward: keeping it and reducing width cannot improve the area.', '[1,8,6,2,5,4,8,3,7] uses indices 1 and 8: width 7 × height 7 = 49.', 'O(n) time, O(1) space.', 'This selects two boundary lines; it does not sum trapped water.', 'Give a proof that discarding the shorter line cannot discard a better pair with that same line.'),
 'product-except-self': ('The forward pass stores products strictly to the left. The backward pass multiplies in products strictly to the right. Neither includes the current value.', '[2,3,4] gets left products [1,2,6], then becomes [12,8,6] after multiplying right products.', 'O(n) time; O(1) auxiliary space excluding the O(n) output.', 'Division fails with zeros. Two zeros correctly produce an all-zero output.', 'Explain the identity product 1 at either end.'),
 'subarray-sum-k': ('If the current prefix is s, each earlier prefix s−k starts a valid subarray. Store frequencies, not just presence, and seed prefix 0 once.', '[1,−1,1], k=1 has prefixes 0,1,0,1. The last prefix matches both earlier zero prefixes: three total subarrays.', 'O(n) expected time, O(n) space.', 'Count matches before recording the current prefix to avoid counting empty subarrays.', 'Return existence instead of count, matching the reported Meta variant.'),
 'daily-temperatures': ('Keep unresolved day indices in decreasing temperature order. A warmer incoming day resolves every colder day at the stack top.', '[70,71,69,73] gives [1,2,1,0]. The 73 resolves both 69 and 71.', 'O(n) time and O(n) space; every index is pushed and popped at most once.', 'Equal temperature is not warmer; store indices to calculate waiting days.', 'Find the next greater value in a circular array.'),
 'valid-parentheses': ('Push opening brackets. Each closing bracket must match the most recent unmatched opener. A valid string also leaves no open brackets behind.', 'For ([{}]), the closes remove {, then [, then (. For ([)], ) conflicts with [ immediately.', 'O(n) time, O(n) space.', 'Checking only counts cannot detect incorrect nesting.', 'Extend the parser to ignore brackets inside quoted strings.'),
 'decode-string': ('Save the outer text and repeat count when entering [. At ], repeat the completed inner text and attach it to the saved outer text. Accumulate digits for multi-digit counts.', '2[a3[b]] first decodes the inner part to abbb, then repeats it to abbbabbb.', 'Time and space depend on expanded output; repeated immutable-string concatenation can add quadratic copying.', 'Reset the digit accumulator and current text on entering a nested block.', 'Reject expansions beyond a maximum output length before allocating them.'),
 'validate-bst': ('Pass an allowed open interval down the tree. A left descendant must remain below every ancestor upper bound, not only its parent.', '[5,1,7,null,null,4,8] is invalid because 4 is in the right subtree of 5.', 'O(n) time, O(h) recursion space for height h.', 'Parent-only comparisons miss violations deeper in the tree; duplicates are disallowed here.', 'Implement iterative inorder traversal to avoid recursion depth limits.'),
 'max-depth': ('An empty subtree has height zero. A nonempty subtree has one level plus the larger child height.', '[3,9,20,null,null,15,7] has depths 1,2,3; maximum depth is 3.', 'O(n) time, O(h) recursion space.', 'Count nodes/levels, not edges, under this contract.', 'Use breadth-first levels for an iterative version.'),
 'num-islands': ('Each unvisited land cell starts a new connected component. Flood-fill its four-direction neighbors so that component is counted once.', 'In [[1,0],[0,1]], diagonal cells are disconnected, so there are two islands.', 'O(RC) time, O(RC) worst-case stack space.', 'The supplied grid uses string cells. Mark when discovering a cell to prevent repeated work.', 'Count distinct island shapes or implement a non-mutating visited-set version.'),
 'rotting-oranges': ('Start BFS with every rotten orange. Process one entire frontier per minute so infection spreads simultaneously.', 'In [[2,1,1]], the middle rots at minute 1 and the last at minute 2.', 'O(RC) time, O(RC) queue space.', 'Unreachable fresh cells require −1. With no fresh cells the answer is zero.', 'Return each cell’s infection time.'),
 'course-schedule': ('Indegree counts unfinished prerequisites. Begin with zero-indegree courses; removing one releases its dependents. Processing every course means there is no cycle.', 'Edges 0→1 and 1→2 release 0,1,2 in turn. Adding 2→0 leaves no starting node.', 'O(V+E) time and space.', 'A disconnected cycle still makes the entire schedule impossible.', 'Return an actual order, with an explicit tie rule.'),
 'merge-k-sorted': ('The heap contains the next unconsumed element of each sorted input. Pop the smallest, append it, and advance only that input.', 'For [[1,4],[2,3]], the heap emits 1,2,3,4 while preserving each input’s order.', 'O(N log k) time, O(k) auxiliary space plus O(N) output.', 'This local version uses arrays, not linked-list nodes, and preserves duplicates.', 'The Meta report used three arrays and required deduplication; solve that variant separately.'),
 'subsets': ('For each value, copy every existing subset and append that value. The old subsets omit it; the new subsets contain it.', 'Start [[]]. After 1: [[],[1]]. After 2 add [2] and [1,2].', 'O(n·2^n) time and output space.', 'Append copies, not the same mutable list. Inputs are distinct.', 'Handle repeated input values without duplicate subsets.'),
 'word-search': ('Try every starting cell. Mark a cell as used for the current path, explore four neighbors for the next letter, then restore it before returning.', 'On [[a,b]], ba succeeds by moving left; aba fails because it would reuse the a cell.', 'Loose bound O(RC·4^L) time, O(L) recursion space for word length L.', 'Visited cells must be local to one path; restore the board when backtracking.', 'Search many words at once using a trie.'),
 'unique-paths': ('The path count to a cell equals the count from above plus the count from the left. A one-row array holds the previous row until each entry is updated.', 'For a 2×3 grid, start [1,1,1], then update to [1,2,3]; there are 3 paths.', 'O(mn) time, O(n) space.', 'Update left to right so dp[j−1] is already the current row.', 'Add blocked cells, setting their path count to zero.'),
 'climb-stairs': ('The last move is either one step or two. Their possibilities do not overlap, so ways(n)=ways(n−1)+ways(n−2). Keep just the last two values.', 'For n=4, ways(2)=2 and ways(3)=3, so ways(4)=5.', 'O(n) time, O(1) auxiliary integer slots; big-integer costs grow with n.', 'The intended domain is n≥1. Clarify what zero steps should mean before extending it.', 'Allow a custom set of step sizes.'),
 'house-robber': ('At each house compare skipping it with taking its value plus the best total ending before the previous house. Update both saved totals together.', '[2,7,9,3,1] leads to best totals 2,7,11,11,12.', 'O(n) time, O(1) auxiliary space.', 'Greedily taking the largest local house can block a better pair.', 'Make the houses circular and solve two linear cases.'),
 'word-break': ('dp[i] means the first i characters can be segmented. Try each split j: a valid prefix ending at j plus a dictionary word s[j:i] proves dp[i].', 'For catsdog and [cats,dog], dp[4] becomes true, then dp[7] becomes true from split 4.', 'O(n³) worst-case Python time due to substring copying/hashing; O(n+dictionary size) retained space.', 'The empty prefix must be true. A greedy longest word can lead to a dead end.', 'Limit candidate word lengths or use a trie to reduce repeated substring work.'),
 'coin-change': ('Build the best answer for every amount. If coin c fits, extend an optimal solution for amount−c by one coin. Unreachable amounts stay infinite.', 'For [1,3,4] and 6, greedy 4+1+1 uses three; DP finds 3+3 using two.', 'O(amount·number_of_coins) time, O(amount) space.', 'Use positive denominations and return −1 when the final amount stays unreachable.', 'Store a predecessor coin to reconstruct the chosen coins.'),
 'lis': ('tails[i] is the smallest possible ending value of an increasing subsequence of length i+1. Binary search finds the earliest tail to replace.', '[3,1,2] changes tails from [3] to [1] to [1,2], giving length 2.', 'O(n log n) time, O(n) space.', 'Use bisect_left for strictly increasing sequences; repeated values must not increase length.', 'Track predecessor indices to recover an actual subsequence.'),
 'jump-game': ('Maintain the furthest reachable index. If the next index exceeds it, no previously reachable position can get there. Otherwise extend reach with the current jump.', '[2,0,1] reaches index 2 from index 0, so the zero at index 1 is harmless.', 'O(n) time, O(1) space.', 'A zero only blocks you when it is at the current reach boundary.', 'Return the minimum jump count using frontier expansion.'),
 'set-zeroes': ('First record all original zero rows and columns. Then build the result using those sets; newly inserted zeros never influence the scan.', 'A zero at (1,1) in a 3×3 matrix zeros row 1 and column 1 only.', 'O(RC) time; O(R+C) auxiliary space plus O(RC) output.', 'Zeroing during discovery can cascade through the entire matrix.', 'Use the first row and column as markers for an in-place version.'),
 'softmax': ('Subtract the largest logit before exponentiating. This preserves relative probabilities because every exponential gets the same factor, and makes the largest exponent zero.', '[1000,1000] becomes [0,0], then [1,1], then [0.5,0.5] without overflow.', 'O(n) time and space.', 'Inputs must be nonempty finite values. Very negative shifted logits may underflow harmlessly to zero.', 'Add temperature and explain why low temperature sharpens the distribution.'),
 'cosine-sim': ('Take the dot product and divide by both vector lengths. This compares direction while canceling positive changes of scale.', '[3,4] with itself gives 25/(5×5)=1. With [−3,−4] it gives −1.', 'O(d) time, O(1) auxiliary space.', 'Cosine is undefined for a zero vector mathematically; this exercise deliberately returns zero.', 'Rank retrieved documents by cosine and define tie ordering.'),
 'kv-cache': ('Every layer retains a key and a value per token per KV head. Multiply those two tensors’ dimensions by bytes per element.', '2 layers × 2 KV heads × dimension 4 × 10 tokens × 2 bytes × keys-and-values factor 2 = 640 bytes.', 'O(1) arithmetic operations and space.', 'Use KV heads, not query heads, for grouped-query attention. Batch size is omitted in this single-sequence exercise.', 'Include batch size, block rounding, and bytes-to-GiB conversion; verify model configs instead of assuming example head counts.'),
 'tokens-per-sec': ('Estimate an ideal bandwidth ceiling by dividing bytes readable each second by model weight bytes. Convert parameter billions and bits into decimal GB first.', 'A 7B model at 4 bits is approximately 3.5 GB; at 70 GB/s the ideal ceiling is 20 tokens/s.', 'O(1) time and space.', 'This is a rough batch-one weight-bandwidth ceiling, not measured performance; caches, compute, and overhead also matter.', 'Explain why batching changes weight reuse and invalidates a direct per-request extrapolation.'),
 'rrf': ('Each ranked list votes for documents using inverse rank plus a smoothing constant. Sum votes by document ID, then rank combined scores.', 'With k=0 and lists [a,b] and [b], a gets 1 while b gets 1/2+1=1.5, so b ranks first.', 'O(N + u log u) time, O(u) space for N rank entries and u documents.', 'Ranks start at 1. Each individual ranking should contain a document at most once.', 'Compare this rank-based fusion with score normalization across retrievers.'),
 'rslora': ('LoRA scales an adapter update by alpha/r. rsLoRA uses alpha/sqrt(r); at larger ranks it reduces the shrinkage from the denominator.', 'At r=16 and alpha=32, LoRA returns 2 while rsLoRA returns 8.', 'O(1) time and space.', 'Rank must be positive. Scaling alone does not establish fine-tuning quality.', 'Compute an actual low-rank matrix update and compare it with a dense update.'),
 'lru-cache': ('OrderedDict stores items from least to most recently used. Both a successful get and a put move that key to the end; exceeding capacity removes the first item.', 'Capacity 2: put a,b; get a changes order to b,a; put c evicts b.', 'Expected O(1) per get/put; O(capacity) space.', 'Updating an existing key must refresh recency without increasing the number of keys.', 'Implement the same operations with a hash map and doubly linked list, then add expiration.'),
 'trie': ('Each edge represents one character; shared prefixes reuse nodes. A terminal marker distinguishes a complete inserted word from a prefix.', 'Insert apple. search(app) is false, but starts_with(app) is true. Inserting app adds a terminal marker at that node.', 'O(L) per operation; O(total inserted characters) space.', 'The reference reserves $ as its terminal marker, so use lowercase alphabetic words.', 'Support deletion while retaining nodes needed by other words.'),
}
EVIDENCE = {
 'lru-cache': ['amazon20','uber'], 'num-islands': ['amazon20','uber'],
 'kth-largest': ['meta_ml','meta_infra','amazon24'],
 'valid-parentheses': ['ms25'],
}
RELATED = {'merge-k-sorted':['meta_ml'], 'subarray-sum-k':['meta_ml'], 'top-k-frequent':['db_counter']}

def source(key, relation='Reported question / local adaptation'):
    company, title, url, note = SOURCES[key]
    return dict(company=company,title=title,url=url,note=note,relation=relation,checked='2026-10-04')

def explain(parts):
    idea, trace, cost, pitfall, follow = parts
    return f'### How to think about it\n{idea}\n\n### Walk through an example\n{trace}\n\n### Time and space\n{cost}\n\n### Common mistake\n{pitfall}\n\n### Interview follow-up\n{follow}'

def enrich(p):
    p['explanation'] = explain(NOTES[p['id']])
    p['track'] = 'AI / ML implementation' if p['id'] in {'softmax','cosine-sim','kv-cache','tokens-per-sec','rrf','rslora'} else 'Coding fundamentals'
    p['sources'] = [source(k) for k in EVIDENCE.get(p['id'], [])] + [source(k,'Related reported variant') for k in RELATED.get(p['id'], [])]
    p['evidence'] = 'Reported / adapted' if p['sources'] else 'Profile practice'
    p['relevance'] = ('Connects to your résumé’s RAG, model serving, and NoteEchoes work.' if p['track'].startswith('AI') else 'Builds the Python problem-solving fluency needed alongside your AI and backend experience.')
