"""Problem-specific starting approaches before the reference explanation."""
BASELINES = {
  "two-sum": "Start by checking every pair of indices: this costs O(n\u00b2). Notice that for a fixed x the partner is already determined as target\u2212x. A lookup table replaces the repeated partner scan.",
  "three-sum": "Try three nested loops and deduplicate triplets: O(n\u00b3) checks. Sorting lets you fix one number and search the remaining pair with two moving boundaries in O(n\u00b2) overall.",
  "longest-substring": "Try every substring and reject those containing duplicates. Repeated work occurs when adjacent candidate substrings share almost all their characters. Maintain one valid window instead.",
  "min-window": "Enumerate source substrings and count their letters. Most counts repeat between overlapping candidates. Maintain counts while expanding and shrinking one window.",
  "merge-intervals": "Repeatedly find any two overlapping intervals and merge them. Sorting by start makes possible overlaps local: only the last output interval needs comparison.",
  "kth-largest": "Sort the entire array descending and take position k\u22121. That is a useful correct O(n log n) baseline. A bounded heap retains only the k candidates that matter when k is small.",
  "top-k-frequent": "Count all values and sort the distinct values by frequency. The reference uses Counter.most_common to select candidates, then sorts their values to meet the local output contract.",
  "search-rotated": "Scan every value for the target in O(n). To improve this, observe that at least one half of a rotated distinct array is sorted, allowing safe elimination of half the candidates.",
  "max-subarray": "Sum every nonempty subarray. Instead of restarting at every position, keep the best sum ending at the previous position; a new element either extends it or begins a new subarray.",
  "trapping-rain": "For each bar, scan left and right for the tallest boundaries. The limiting height determines its water. Two running maxima recover that information without repeated full scans.",
  "container-water": "Check all O(n\u00b2) pairs. For a fixed shorter boundary, moving the other boundary inward cannot improve area. That observation justifies discarding one endpoint at each step.",
  "product-except-self": "Multiply all other values separately for every index, costing O(n\u00b2). Neighboring outputs share almost the same factors; prefix and suffix products reuse them without division.",
  "subarray-sum-k": "Extend a running sum from every starting index in O(n\u00b2). A subarray sum is a difference of two prefix sums, allowing earlier matching prefixes to be counted by a dictionary.",
  "daily-temperatures": "For each day, scan later days until a warmer one appears. A stack groups unresolved days so each is pushed and resolved at most once.",
  "valid-parentheses": "Repeatedly delete adjacent matching bracket pairs until nothing changes. A stack expresses the same nesting requirement in one pass: the most recent unmatched opener must close first.",
  "decode-string": "Try resolving the innermost bracket pair repeatedly. An explicit stack saves outer contexts as you scan, avoiding repeated searches for the next inner block.",
  "validate-bst": "A tempting first attempt checks each node only against its children. That misses deeper ancestor violations. Carry a full allowed range down each recursive path.",
  "max-depth": "List every root-to-leaf path and take the longest length. Recursion needs only child depths, so it can compute the answer without storing complete paths.",
  "num-islands": "Count land cells first, then recognize that connected cells belong to one island. Flood-fill an entire component whenever a new unvisited land cell is found.",
  "rotting-oranges": "Rescan the whole grid each minute using a copy to preserve simultaneous infection. Multi-source BFS visits only newly reached cells and makes each frontier one minute.",
  "course-schedule": "Try choosing courses in many different orders. Instead, keep only courses with no unfinished prerequisites; failing to release every course reveals a cycle.",
  "merge-k-sorted": "Concatenate arrays and sort all N values in O(N log N). Their existing order allows a heap to choose among only k next candidates.",
  "subsets": "Represent each subset by an n-bit inclusion mask. The iterative reference builds the same choice space by doubling the existing collection for each value.",
  "word-search": "Try paths from every cell. Backtracking prunes a path as soon as its next character disagrees, and a temporary visited marker prevents reusing a cell.",
  "unique-paths": "Recursively branch right and down at every cell. Many branches reach the same cell; dynamic programming stores each cell count once and reuses only one row.",
  "climb-stairs": "Recursively choose one or two steps. The same remaining stair counts recur, so keep just the last two answers instead of recalculating them.",
  "house-robber": "Enumerate subsets and reject adjacent selections. Each house needs only two earlier best totals, capturing the take-or-skip choice without storing subsets.",
  "word-break": "Try every possible sequence of dictionary splits recursively. Mark which prefixes are segmentable so the same prefix is not solved repeatedly.",
  "coin-change": "Try every possible coin sequence. The smallest amount subproblems recur, so compute the best answer for every amount once.",
  "lis": "Enumerate subsequences, then improve to an O(n\u00b2) DP comparing earlier elements. The reference improves further by retaining the smallest tail for every possible length and using binary search.",
  "jump-game": "Explore every reachable jump destination. You only need the farthest position reachable so far to determine whether the next index can be reached.",
  "set-zeroes": "A safe baseline records original zero positions before modifying anything. The reference compresses that evidence into sets of affected rows and columns and returns a new matrix.",
  "softmax": "Apply exp directly to every score and divide by their sum. This overflows for large logits; subtracting one shared maximum preserves the answer while making exponentiation safe.",
  "cosine-sim": "Start with a dot product, then notice that simply scaling one vector changes it. Dividing by both vector lengths isolates direction.",
  "kv-cache": "Draw the stored K and V tensors for one token in one layer. Count their entries, then multiply by layers, tokens, and element bytes rather than memorizing a model-specific number.",
  "tokens-per-sec": "Estimate how many full weight reads fit into one second of memory traffic. Keep units in GB and GB/s before dividing; the result is a ceiling under stated assumptions.",
  "rrf": "Raw scores from different retrievers may use incompatible scales. Start from their rank positions instead and sum a declining vote for each occurrence of a document.",
  "rslora": "Write both scaling definitions before coding: alpha/r and alpha/sqrt(r). The exercise tests selecting and calculating the right rule, not proving a quality improvement.",
  "lru-cache": "Keep a list in recency order and scan it for every lookup. A keyed ordered structure makes lookup, recency movement, and eviction efficient.",
  "trie": "Store complete words in a set, and scan every word for prefix queries. A trie shares prefix paths so both exact and prefix queries follow only the query characters.",
  "meeting-rooms": "Compare each meeting with every other meeting to reason about overlaps. A sorted start scan plus active end-time heap tracks precisely the rooms occupied at each arrival.",
  "min-tree-depth": "Explore every root-to-leaf path and take the smallest depth. BFS can stop sooner: its first leaf is necessarily one of the nearest.",
  "vertical-order": "Collect nodes with coordinates, then sort by column and depth, taking care with ties. BFS supplies the row and tie order naturally while column lists collect values.",
  "restore-ip": "Try all positions for three dots and validate each result. Backtracking additionally prunes prefixes when remaining characters cannot fit the remaining parts.",
  "nested-weight": "For a fixed nesting depth you might write nested loops, but arbitrary depth needs recursion or a stack. Carrying depth makes every integer contribution explicit.",
  "merge-unique": "Combine values in a set and sort it. A lazy merge exploits sorted inputs; adjacent equal emitted values can be skipped using only the last kept value.",
  "logger-cooldown": "For each event scan earlier accepted events for the same message. Store only the most recent accepted time per message to make that decision immediate.",
  "recipe-dependencies": "Repeatedly scan every recipe until no new one becomes available. Reverse dependency lists let an available ingredient notify only the recipes waiting for it.",
  "sparse-matvec": "Build a dense matrix and multiply every cell by its matching vector value. Zero cells contribute nothing, so process only stored coordinates.",
  "lazy-map": "Transform the entire array through every map, then search. Evaluating one element through the chain at a time lets the first match stop all later work.",
  "hit-counter": "Keep all historical hits and scan them for every count. Ordered timestamps allow expired entries to leave a deque once and never be reconsidered.",
  "bounded-crawler": "Follow links recursively and limit path length. BFS ensures the first visit is by a shortest path, which is important when a depth budget restricts later expansion.",
  "resumable-iterator": "A normal iterator hides its cursor. Define the saved state as the next unread index, then implement reads and restoration around that precise meaning.",
  "mini-database": "Separate the task into equality filtering and ordering before adding any database machinery. The simple scan-and-sort is appropriate here; indexes are a later optimization.",
  "ttl-lru": "Begin with an ordinary LRU cache, then add an expiry timestamp to each entry. This reference uses a clear expiration scan first; optimizing that scan is a separate follow-up.",
  "word-abbreviation": "You could expand numeric skips into placeholders, but that allocates unnecessary text. Advance a word cursor directly by the parsed skip count.",
  "fast-power": "Multiply x by itself |n| times, then invert for a negative exponent. Squaring the base and consuming exponent bits reduces the number of multiplications.",
  "min-stack": "Store values in a list and call min on every minimum query. Remember a prefix minimum at each stack position so removing an item also restores the previous minimum.",
  "generate-parentheses": "Generate all length-2n parenthesis strings and filter valid ones. Enforcing legal open/close counts while building the string prevents invalid prefixes from expanding.",
  "find-duplicate": "Use a set to find repeats, which needs linear memory. The constrained value range also forms a pointer graph, so cycle detection can locate the duplicate with constant space.",
  "sparse-dot": "Build dense arrays across all coordinates and multiply corresponding entries. Only shared nonzero coordinates matter, so scan the smaller sparse dictionary.",
  "nearest-neighbors": "The exact scan-and-sort is the deliberate correctness baseline. Keep it to evaluate a faster heap or approximate index against known exact neighbors.",
  "kmeans-step": "Assign each point to the nearest old center, then recompute group means. The essential design choice is to separate those phases rather than moving centers during assignment.",
  "linear-gradient": "Write the mean squared loss on paper and differentiate it. Accumulate one full gradient before applying updates, so every row sees the same current weights.",
  "stable-sigmoid": "Use the textbook 1/(1+exp(\u2212x)), then test x=\u22121000. An equivalent expression for negative x avoids overflowing exp(1000).",
  "binary-log-loss": "Convert logits to probabilities and then take logarithms. Extreme probabilities round to zero or one; an algebraically combined logit-space expression avoids log(0).",
  "classification-metrics": "Write a small confusion table by hand before coding. The counts make it clear which denominator belongs to precision, recall, and F1.",
  "confusion-matrix": "Keep a tally for each actual/predicted label pair. A square matrix is a direct indexed version of that tally with an explicit row/column meaning.",
  "recall-at-k": "Manually mark relevant documents among the first k positions. Set intersection expresses that count while preventing duplicate results from earning repeated credit.",
  "ndcg": "Count relevant results, then notice that a high-grade result at the top is more useful than one at the bottom. Add rank discounts and normalize by the best ordering.",
  "overlap-chunks": "Slice nonoverlapping blocks first, then introduce overlap by reducing the start-position increment. Stop when a chunk already covers the final token.",
  "tfidf": "Count words in each document, then ask which words also appear almost everywhere. IDF reduces the relative contribution of those common terms.",
  "attention": "Compare the query with each key, normalize those comparisons, then mix values. Keep these three stages separate before compressing them into a matrix formula.",
  "layer-norm": "Compute the mean and squared deviations by hand for a tiny vector. Use population variance and epsilon, then apply the same centering and scale to every coordinate.",
  "token-batches": "Put one request in every batch for a trivially safe baseline. Fill a batch until the next request would break the budget, while retaining arrival order.",
  "request-dedup": "Compare raw request strings, then observe that harmless key-order or whitespace changes break equality. Parse and canonicalize object data before comparing.",
  "subscription-events": "Write the events for one subscription by hand. Generate those same events independently for every subscription, then sort the combined schedule.",
  "token-bucket": "Start with a fixed request allowance, then make it recover with elapsed time. Tracking last refill time and current tokens avoids counting every prior request.",
  "dense-rank": "Sort each group's rows and reason through ties. Mapping distinct scores to consecutive ranks then allows results to be returned in the original row order.",
  "bounded-async": "Run each awaitable job sequentially for a correct but potentially slow I/O baseline. A fixed worker pool overlaps waits while bounding the number of live tasks.",
  "confidence-abstention": "Choosing the largest score always produces an answer even when the model is unsure. Add explicit score and separation criteria so abstention is a first-class outcome.",
  "field-validation": "Checking that the JSON parses says nothing about required field contents. Validate existence, type, and trimmed content before separate business-rule checks.",
  "action-receipts": "Executing every retry repeats side effects. Bind an operation ID to its original payload and replay the receipt, but only after authorization and cancellation checks.",
  "pagerank-step": "First distribute rank across outgoing edges by hand. Add teleport mass and dangling-node redistribution to keep the probability total from vanishing."
}
